<a href="https://colab.research.google.com/github/saikrishna9917/AIML/blob/master/ASSIGNMENT_17_%5B16_06_2020%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ASSIGNMENT-17[16-06-2020]

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
data3=pd.read_csv("https://data.princeton.edu/wws509/datasets/salary.dat",sep=" ")
data3

    Unnamed: 0 Unnamed: 1 Unnamed: 2  ... Unnamed: 25 Unnamed: 26  sl
0          NaN        NaN        NaN  ...         NaN         NaN NaN
1          NaN        NaN        NaN  ...         NaN         NaN NaN
2          NaN        NaN        NaN  ...         NaN         NaN NaN
3          NaN     female        NaN  ...         NaN         NaN NaN
4          NaN        NaN        NaN  ...         NaN         NaN NaN
5          NaN        NaN        NaN  ...         NaN         NaN NaN
6          NaN     female        NaN  ...         NaN         NaN NaN
7          NaN        NaN        NaN  ...         NaN         NaN NaN
8          NaN        NaN        NaN  ...         NaN         NaN NaN
9          NaN        NaN        NaN  ...         NaN         NaN NaN
10         NaN        NaN        NaN  ...         NaN         NaN NaN
11         NaN        NaN        NaN  ...         NaN         NaN NaN
12         NaN        NaN        NaN  ...         NaN         NaN NaN
13         NaN        NaN        NaN  ...         NaN         NaN NaN
14         NaN        NaN        NaN  ...         NaN         NaN NaN
15         NaN        NaN        NaN  ...         NaN         NaN NaN
16         NaN        NaN        NaN  ...         NaN         NaN NaN
17         NaN        NaN        NaN  ...         NaN         NaN NaN
18         NaN        NaN        NaN  ...         NaN         NaN NaN
19         NaN        NaN        NaN  ...         NaN         NaN NaN
20         NaN        NaN        NaN  ...         NaN         NaN NaN
21         NaN        NaN        NaN  ...         NaN         NaN NaN
22         NaN        NaN        NaN  ...         NaN         NaN NaN
23         NaN     female        NaN  ...         NaN         NaN NaN
24         NaN        NaN        NaN  ...         NaN         NaN NaN
25         NaN        NaN        NaN  ...         NaN         NaN NaN
26         NaN        NaN        NaN  ...         NaN         NaN NaN
27         NaN     female        NaN  ...         NaN         NaN NaN
28         NaN        NaN        NaN  ...         NaN         NaN NaN
29         NaN        NaN        NaN  ...         NaN         NaN NaN
30         NaN     female  assistant  ...         NaN         NaN NaN
31         NaN        NaN        NaN  ...         NaN         NaN NaN
32         NaN        NaN        NaN  ...         NaN         NaN NaN
33         NaN     female  associate  ...         NaN         NaN NaN
34         NaN     female  associate  ...         NaN         NaN NaN
35         NaN        NaN        NaN  ...         NaN         NaN NaN
36         NaN     female  assistant  ...         NaN         NaN NaN
37         NaN        NaN        NaN  ...         NaN         NaN NaN
38         NaN        NaN        NaN  ...         NaN         NaN NaN
39         NaN        NaN        NaN  ...         NaN         NaN NaN
40         NaN        NaN        NaN  ...         NaN         NaN NaN
41         NaN        NaN        NaN  ...         NaN         NaN NaN
42         NaN        NaN        NaN  ...         NaN         NaN NaN
43         NaN     female  assistant  ...         NaN         NaN NaN
44         NaN        NaN        NaN  ...         NaN         NaN NaN
45         NaN        NaN        NaN  ...         NaN         NaN NaN
46         NaN     female  assistant  ...         NaN         NaN NaN
47         NaN     female  assistant  ...         NaN         NaN NaN
48         NaN        NaN        NaN  ...         NaN         NaN NaN
49         NaN     female  assistant  ...         NaN         NaN NaN
50         NaN     female  assistant  ...         NaN         NaN NaN
51         NaN     female  assistant  ...         NaN         NaN NaN

[52 rows x 28 columns]

In [3]:
#Check for any missing values in the dataset
data3.apply(lambda x:x.isnull().sum(),axis=0)

Unnamed: 0     52
Unnamed: 1     38
Unnamed: 2     42
Unnamed: 3     13
Unnamed: 4     21
sx             39
Unnamed: 6     32
Unnamed: 7     26
Unnamed: 8     36
Unnamed: 9     10
Unnamed: 10    21
Unnamed: 11    30
Unnamed: 12    35
rk             36
yr             42
Unnamed: 15    48
Unnamed: 16    51
Unnamed: 17    52
Unnamed: 18    52
Unnamed: 19    52
Unnamed: 20    52
Unnamed: 21    52
dg             52
yd             52
Unnamed: 24    52
Unnamed: 25    52
Unnamed: 26    52
sl             52
dtype: int64

In [4]:
data3.dtypes

Unnamed: 0     float64
Unnamed: 1      object
Unnamed: 2      object
Unnamed: 3      object
Unnamed: 4      object
sx              object
Unnamed: 6      object
Unnamed: 7      object
Unnamed: 8      object
Unnamed: 9      object
Unnamed: 10     object
Unnamed: 11     object
Unnamed: 12     object
rk              object
yr              object
Unnamed: 15    float64
Unnamed: 16    float64
Unnamed: 17    float64
Unnamed: 18    float64
Unnamed: 19    float64
Unnamed: 20    float64
Unnamed: 21    float64
dg             float64
yd             float64
Unnamed: 24    float64
Unnamed: 25    float64
Unnamed: 26    float64
sl             float64
dtype: object

In [5]:
#Display the data of only the non-numerical columns
data3.select_dtypes(include=['object'])

   Unnamed: 1 Unnamed: 2 Unnamed: 3  ... Unnamed: 12       rk       yr
0         NaN        NaN       male  ...          35    36350      NaN
1         NaN        NaN       male  ...          22    35350      NaN
2         NaN        NaN       male  ...          23    28200      NaN
3      female        NaN        NaN  ...       26775      NaN      NaN
4         NaN        NaN       male  ...         NaN  masters       30
5         NaN        NaN       male  ...          21    28516      NaN
6      female        NaN        NaN  ...     masters       32    24900
7         NaN        NaN       male  ...          18    31909      NaN
8         NaN        NaN       male  ...         NaN  masters       30
9         NaN        NaN       male  ...         NaN  masters       31
10        NaN        NaN       male  ...          22    27025      NaN
11        NaN        NaN       male  ...         NaN      NaN      NaN
12        NaN        NaN       male  ...   doctorate       17    28200
13        NaN        NaN       male  ...         NaN      NaN      NaN
14        NaN        NaN       male  ...   doctorate       24    25748
15        NaN        NaN       male  ...   doctorate       15    29342
16        NaN        NaN       male  ...          20    31114      NaN
17        NaN        NaN       male  ...         NaN      NaN      NaN
18        NaN        NaN       male  ...         NaN      NaN      NaN
19        NaN        NaN       male  ...         NaN      NaN  masters
20        NaN        NaN       male  ...         NaN      NaN      NaN
21        NaN        NaN       male  ...         NaN      NaN      NaN
22        NaN        NaN       male  ...   doctorate       13    27959
23     female        NaN        NaN  ...       38045      NaN      NaN
24        NaN        NaN       male  ...         NaN      NaN      NaN
25        NaN        NaN       male  ...   doctorate       18    25400
26        NaN        NaN       male  ...         NaN      NaN      NaN
27     female        NaN        NaN  ...       25500      NaN      NaN
28        NaN        NaN       male  ...       26182      NaN      NaN
29        NaN        NaN       male  ...         NaN      NaN      NaN
30     female  assistant         10  ...         NaN      NaN      NaN
31        NaN        NaN       male  ...         NaN      NaN      NaN
32        NaN        NaN       male  ...         NaN      NaN      NaN
33     female  associate        NaN  ...         NaN      NaN      NaN
34     female  associate        NaN  ...         NaN      NaN      NaN
35        NaN        NaN       male  ...         NaN      NaN      NaN
36     female  assistant        NaN  ...         NaN      NaN      NaN
37        NaN        NaN       male  ...         NaN      NaN      NaN
38        NaN        NaN       male  ...         NaN      NaN      NaN
39        NaN        NaN       male  ...         NaN      NaN      NaN
40        NaN        NaN       male  ...         NaN      NaN      NaN
41        NaN        NaN       male  ...         NaN      NaN      NaN
42        NaN        NaN       male  ...         NaN      NaN      NaN
43     female  assistant        NaN  ...         NaN      NaN      NaN
44        NaN        NaN       male  ...         NaN      NaN      NaN
45        NaN        NaN       male  ...         NaN      NaN      NaN
46     female  assistant        NaN  ...         NaN      NaN      NaN
47     female  assistant        NaN  ...         NaN      NaN      NaN
48        NaN        NaN       male  ...         NaN      NaN      NaN
49     female  assistant        NaN  ...         NaN      NaN      NaN
50     female  assistant        NaN  ...         NaN      NaN      NaN
51     female  assistant        NaN  ...         NaN      NaN      NaN

[52 rows x 14 columns]

In [6]:
#Display the data of only the numerical columns
data3.select_dtypes(include=['float64'])

    Unnamed: 0  Unnamed: 15  Unnamed: 16  ...  Unnamed: 25  Unnamed: 26  sl
0          NaN          NaN          NaN  ...          NaN          NaN NaN
1          NaN          NaN          NaN  ...          NaN          NaN NaN
2          NaN          NaN          NaN  ...          NaN          NaN NaN
3          NaN          NaN          NaN  ...          NaN          NaN NaN
4          NaN      33696.0          NaN  ...          NaN          NaN NaN
5          NaN          NaN          NaN  ...          NaN          NaN NaN
6          NaN          NaN          NaN  ...          NaN          NaN NaN
7          NaN          NaN          NaN  ...          NaN          NaN NaN
8          NaN      31850.0          NaN  ...          NaN          NaN NaN
9          NaN      32850.0          NaN  ...          NaN          NaN NaN
10         NaN          NaN          NaN  ...          NaN          NaN NaN
11         NaN          NaN          NaN  ...          NaN          NaN NaN
12         NaN          NaN          NaN  ...          NaN          NaN NaN
13         NaN          NaN          NaN  ...          NaN          NaN NaN
14         NaN          NaN          NaN  ...          NaN          NaN NaN
15         NaN          NaN          NaN  ...          NaN          NaN NaN
16         NaN          NaN          NaN  ...          NaN          NaN NaN
17         NaN          NaN          NaN  ...          NaN          NaN NaN
18         NaN          NaN          NaN  ...          NaN          NaN NaN
19         NaN         21.0      24450.0  ...          NaN          NaN NaN
20         NaN          NaN          NaN  ...          NaN          NaN NaN
21         NaN          NaN          NaN  ...          NaN          NaN NaN
22         NaN          NaN          NaN  ...          NaN          NaN NaN
23         NaN          NaN          NaN  ...          NaN          NaN NaN
24         NaN          NaN          NaN  ...          NaN          NaN NaN
25         NaN          NaN          NaN  ...          NaN          NaN NaN
26         NaN          NaN          NaN  ...          NaN          NaN NaN
27         NaN          NaN          NaN  ...          NaN          NaN NaN
28         NaN          NaN          NaN  ...          NaN          NaN NaN
29         NaN          NaN          NaN  ...          NaN          NaN NaN
30         NaN          NaN          NaN  ...          NaN          NaN NaN
31         NaN          NaN          NaN  ...          NaN          NaN NaN
32         NaN          NaN          NaN  ...          NaN          NaN NaN
33         NaN          NaN          NaN  ...          NaN          NaN NaN
34         NaN          NaN          NaN  ...          NaN          NaN NaN
35         NaN          NaN          NaN  ...          NaN          NaN NaN
36         NaN          NaN          NaN  ...          NaN          NaN NaN
37         NaN          NaN          NaN  ...          NaN          NaN NaN
38         NaN          NaN          NaN  ...          NaN          NaN NaN
39         NaN          NaN          NaN  ...          NaN          NaN NaN
40         NaN          NaN          NaN  ...          NaN          NaN NaN
41         NaN          NaN          NaN  ...          NaN          NaN NaN
42         NaN          NaN          NaN  ...          NaN          NaN NaN
43         NaN          NaN          NaN  ...          NaN          NaN NaN
44         NaN          NaN          NaN  ...          NaN          NaN NaN
45         NaN          NaN          NaN  ...          NaN          NaN NaN
46         NaN          NaN          NaN  ...          NaN          NaN NaN
47         NaN          NaN          NaN  ...          NaN          NaN NaN
48         NaN          NaN          NaN  ...          NaN          NaN NaN
49         NaN          NaN          NaN  ...          NaN          NaN NaN
50         NaN          NaN          NaN  ...          NaN          NaN NaN
51         NaN          NaN          NaN  ...          NaN          NaN NaN

[52 rows x 14 columns]

In [7]:
#Get a list of categorical variables with the categories frequency count.
data3.apply(pd.value_counts)

           Unnamed: 0  Unnamed: 1  Unnamed: 2  ...  Unnamed: 25  Unnamed: 26  sl
21.0              NaN         NaN         NaN  ...          NaN          NaN NaN
24450.0           NaN         NaN         NaN  ...          NaN          NaN NaN
31850.0           NaN         NaN         NaN  ...          NaN          NaN NaN
32850.0           NaN         NaN         NaN  ...          NaN          NaN NaN
33696.0           NaN         NaN         NaN  ...          NaN          NaN NaN
...               ...         ...         ...  ...          ...          ...  ..
doctorate         NaN         NaN         NaN  ...          NaN          NaN NaN
female            NaN        14.0         NaN  ...          NaN          NaN NaN
full              NaN         NaN         NaN  ...          NaN          NaN NaN
male              NaN         NaN         NaN  ...          NaN          NaN NaN
masters           NaN         NaN         NaN  ...          NaN          NaN NaN

[92 rows x 28 columns]

In [8]:
#Create dummy variables for the columns sx and dg
data4=pd.get_dummies(data3.sx)
data4

    10  11  15  16  doctorate
0    0   0   0   0          0
1    0   0   0   0          0
2    0   0   0   0          0
3    0   0   0   0          0
4    0   0   0   0          0
5    0   0   0   0          0
6    0   0   0   0          0
7    0   0   0   0          0
8    0   0   0   0          0
9    0   0   0   0          0
10   0   0   0   0          0
11   0   0   1   0          0
12   0   0   0   0          0
13   0   0   0   0          0
14   0   0   0   0          0
15   0   0   0   0          0
16   0   0   0   0          0
17   0   1   0   0          0
18   1   0   0   0          0
19   0   0   0   0          0
20   0   0   0   1          0
21   0   0   0   0          0
22   0   0   0   0          0
23   0   0   0   0          0
24   0   0   0   0          0
25   0   0   0   0          0
26   0   1   0   0          0
27   0   0   0   0          0
28   0   0   0   0          0
29   0   0   0   0          0
30   0   0   0   0          0
31   0   1   0   0          0
32   0   0   0   0          0
33   0   0   0   0          0
34   0   0   0   0          0
35   0   0   0   0          0
36   0   0   0   0          1
37   0   0   0   0          0
38   0   0   0   0          0
39   0   0   0   0          0
40   0   0   0   0          0
41   0   0   0   0          0
42   0   0   0   0          0
43   0   0   0   0          1
44   0   0   0   0          0
45   0   0   0   0          0
46   0   0   0   0          1
47   0   0   0   0          1
48   0   0   0   0          0
49   0   0   0   0          1
50   0   0   0   0          1
51   0   0   0   0          1

In [9]:
data5=pd.get_dummies(data3.dg)
data5

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]

In [10]:
#Create a dataframe by adding dummy variables to the original data frame using concat.
df=pd.concat([data3,data4],axis=1)
df

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  ... 11 15 16 doctorate
0          NaN        NaN        NaN       male  ...  0  0  0         0
1          NaN        NaN        NaN       male  ...  0  0  0         0
2          NaN        NaN        NaN       male  ...  0  0  0         0
3          NaN     female        NaN        NaN  ...  0  0  0         0
4          NaN        NaN        NaN       male  ...  0  0  0         0
5          NaN        NaN        NaN       male  ...  0  0  0         0
6          NaN     female        NaN        NaN  ...  0  0  0         0
7          NaN        NaN        NaN       male  ...  0  0  0         0
8          NaN        NaN        NaN       male  ...  0  0  0         0
9          NaN        NaN        NaN       male  ...  0  0  0         0
10         NaN        NaN        NaN       male  ...  0  0  0         0
11         NaN        NaN        NaN       male  ...  0  1  0         0
12         NaN        NaN        NaN       male  ...  0  0  0         0
13         NaN        NaN        NaN       male  ...  0  0  0         0
14         NaN        NaN        NaN       male  ...  0  0  0         0
15         NaN        NaN        NaN       male  ...  0  0  0         0
16         NaN        NaN        NaN       male  ...  0  0  0         0
17         NaN        NaN        NaN       male  ...  1  0  0         0
18         NaN        NaN        NaN       male  ...  0  0  0         0
19         NaN        NaN        NaN       male  ...  0  0  0         0
20         NaN        NaN        NaN       male  ...  0  0  1         0
21         NaN        NaN        NaN       male  ...  0  0  0         0
22         NaN        NaN        NaN       male  ...  0  0  0         0
23         NaN     female        NaN        NaN  ...  0  0  0         0
24         NaN        NaN        NaN       male  ...  0  0  0         0
25         NaN        NaN        NaN       male  ...  0  0  0         0
26         NaN        NaN        NaN       male  ...  1  0  0         0
27         NaN     female        NaN        NaN  ...  0  0  0         0
28         NaN        NaN        NaN       male  ...  0  0  0         0
29         NaN        NaN        NaN       male  ...  0  0  0         0
30         NaN     female  assistant         10  ...  0  0  0         0
31         NaN        NaN        NaN       male  ...  1  0  0         0
32         NaN        NaN        NaN       male  ...  0  0  0         0
33         NaN     female  associate        NaN  ...  0  0  0         0
34         NaN     female  associate        NaN  ...  0  0  0         0
35         NaN        NaN        NaN       male  ...  0  0  0         0
36         NaN     female  assistant        NaN  ...  0  0  0         1
37         NaN        NaN        NaN       male  ...  0  0  0         0
38         NaN        NaN        NaN       male  ...  0  0  0         0
39         NaN        NaN        NaN       male  ...  0  0  0         0
40         NaN        NaN        NaN       male  ...  0  0  0         0
41         NaN        NaN        NaN       male  ...  0  0  0         0
42         NaN        NaN        NaN       male  ...  0  0  0         0
43         NaN     female  assistant        NaN  ...  0  0  0         1
44         NaN        NaN        NaN       male  ...  0  0  0         0
45         NaN        NaN        NaN       male  ...  0  0  0         0
46         NaN     female  assistant        NaN  ...  0  0  0         1
47         NaN     female  assistant        NaN  ...  0  0  0         1
48         NaN        NaN        NaN       male  ...  0  0  0         0
49         NaN     female  assistant        NaN  ...  0  0  0         1
50         NaN     female  assistant        NaN  ...  0  0  0         1
51         NaN     female  assistant        NaN  ...  0  0  0         1

[52 rows x 33 columns]

In [11]:
df1=pd.concat([df,data5],axis=1)
df1

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  ... 11 15 16 doctorate
0          NaN        NaN        NaN       male  ...  0  0  0         0
1          NaN        NaN        NaN       male  ...  0  0  0         0
2          NaN        NaN        NaN       male  ...  0  0  0         0
3          NaN     female        NaN        NaN  ...  0  0  0         0
4          NaN        NaN        NaN       male  ...  0  0  0         0
5          NaN        NaN        NaN       male  ...  0  0  0         0
6          NaN     female        NaN        NaN  ...  0  0  0         0
7          NaN        NaN        NaN       male  ...  0  0  0         0
8          NaN        NaN        NaN       male  ...  0  0  0         0
9          NaN        NaN        NaN       male  ...  0  0  0         0
10         NaN        NaN        NaN       male  ...  0  0  0         0
11         NaN        NaN        NaN       male  ...  0  1  0         0
12         NaN        NaN        NaN       male  ...  0  0  0         0
13         NaN        NaN        NaN       male  ...  0  0  0         0
14         NaN        NaN        NaN       male  ...  0  0  0         0
15         NaN        NaN        NaN       male  ...  0  0  0         0
16         NaN        NaN        NaN       male  ...  0  0  0         0
17         NaN        NaN        NaN       male  ...  1  0  0         0
18         NaN        NaN        NaN       male  ...  0  0  0         0
19         NaN        NaN        NaN       male  ...  0  0  0         0
20         NaN        NaN        NaN       male  ...  0  0  1         0
21         NaN        NaN        NaN       male  ...  0  0  0         0
22         NaN        NaN        NaN       male  ...  0  0  0         0
23         NaN     female        NaN        NaN  ...  0  0  0         0
24         NaN        NaN        NaN       male  ...  0  0  0         0
25         NaN        NaN        NaN       male  ...  0  0  0         0
26         NaN        NaN        NaN       male  ...  1  0  0         0
27         NaN     female        NaN        NaN  ...  0  0  0         0
28         NaN        NaN        NaN       male  ...  0  0  0         0
29         NaN        NaN        NaN       male  ...  0  0  0         0
30         NaN     female  assistant         10  ...  0  0  0         0
31         NaN        NaN        NaN       male  ...  1  0  0         0
32         NaN        NaN        NaN       male  ...  0  0  0         0
33         NaN     female  associate        NaN  ...  0  0  0         0
34         NaN     female  associate        NaN  ...  0  0  0         0
35         NaN        NaN        NaN       male  ...  0  0  0         0
36         NaN     female  assistant        NaN  ...  0  0  0         1
37         NaN        NaN        NaN       male  ...  0  0  0         0
38         NaN        NaN        NaN       male  ...  0  0  0         0
39         NaN        NaN        NaN       male  ...  0  0  0         0
40         NaN        NaN        NaN       male  ...  0  0  0         0
41         NaN        NaN        NaN       male  ...  0  0  0         0
42         NaN        NaN        NaN       male  ...  0  0  0         0
43         NaN     female  assistant        NaN  ...  0  0  0         1
44         NaN        NaN        NaN       male  ...  0  0  0         0
45         NaN        NaN        NaN       male  ...  0  0  0         0
46         NaN     female  assistant        NaN  ...  0  0  0         1
47         NaN     female  assistant        NaN  ...  0  0  0         1
48         NaN        NaN        NaN       male  ...  0  0  0         0
49         NaN     female  assistant        NaN  ...  0  0  0         1
50         NaN     female  assistant        NaN  ...  0  0  0         1
51         NaN     female  assistant        NaN  ...  0  0  0         1

[52 rows x 33 columns]

In [12]:
#Create another  dataframe by adding dummy variables to the original data frame using merge
data1=pd.merge(df1,data3)
data1

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  ... 11 15 16 doctorate
0          NaN        NaN        NaN       male  ...  0  0  0         0
1          NaN        NaN        NaN       male  ...  0  0  0         0
2          NaN        NaN        NaN       male  ...  0  0  0         0
3          NaN     female        NaN        NaN  ...  0  0  0         0
4          NaN        NaN        NaN       male  ...  0  0  0         0
5          NaN        NaN        NaN       male  ...  0  0  0         0
6          NaN     female        NaN        NaN  ...  0  0  0         0
7          NaN        NaN        NaN       male  ...  0  0  0         0
8          NaN        NaN        NaN       male  ...  0  0  0         0
9          NaN        NaN        NaN       male  ...  0  0  0         0
10         NaN        NaN        NaN       male  ...  0  0  0         0
11         NaN        NaN        NaN       male  ...  0  1  0         0
12         NaN        NaN        NaN       male  ...  0  0  0         0
13         NaN        NaN        NaN       male  ...  0  0  0         0
14         NaN        NaN        NaN       male  ...  0  0  0         0
15         NaN        NaN        NaN       male  ...  0  0  0         0
16         NaN        NaN        NaN       male  ...  0  0  0         0
17         NaN        NaN        NaN       male  ...  1  0  0         0
18         NaN        NaN        NaN       male  ...  0  0  0         0
19         NaN        NaN        NaN       male  ...  0  0  0         0
20         NaN        NaN        NaN       male  ...  0  0  1         0
21         NaN        NaN        NaN       male  ...  0  0  0         0
22         NaN        NaN        NaN       male  ...  0  0  0         0
23         NaN     female        NaN        NaN  ...  0  0  0         0
24         NaN        NaN        NaN       male  ...  0  0  0         0
25         NaN        NaN        NaN       male  ...  0  0  0         0
26         NaN        NaN        NaN       male  ...  1  0  0         0
27         NaN     female        NaN        NaN  ...  0  0  0         0
28         NaN        NaN        NaN       male  ...  0  0  0         0
29         NaN        NaN        NaN       male  ...  0  0  0         0
30         NaN     female  assistant         10  ...  0  0  0         0
31         NaN        NaN        NaN       male  ...  1  0  0         0
32         NaN        NaN        NaN       male  ...  0  0  0         0
33         NaN     female  associate        NaN  ...  0  0  0         0
34         NaN     female  associate        NaN  ...  0  0  0         0
35         NaN        NaN        NaN       male  ...  0  0  0         0
36         NaN     female  assistant        NaN  ...  0  0  0         1
37         NaN        NaN        NaN       male  ...  0  0  0         0
38         NaN        NaN        NaN       male  ...  0  0  0         0
39         NaN        NaN        NaN       male  ...  0  0  0         0
40         NaN        NaN        NaN       male  ...  0  0  0         0
41         NaN        NaN        NaN       male  ...  0  0  0         0
42         NaN        NaN        NaN       male  ...  0  0  0         0
43         NaN     female  assistant        NaN  ...  0  0  0         1
44         NaN        NaN        NaN       male  ...  0  0  0         0
45         NaN        NaN        NaN       male  ...  0  0  0         0
46         NaN     female  assistant        NaN  ...  0  0  0         1
47         NaN     female  assistant        NaN  ...  0  0  0         1
48         NaN        NaN        NaN       male  ...  0  0  0         0
49         NaN     female  assistant        NaN  ...  0  0  0         1
50         NaN     female  assistant        NaN  ...  0  0  0         1
51         NaN     female  assistant        NaN  ...  0  0  0         1

[52 rows x 33 columns]

In [13]:
#After adding the dummy columns to the dataframe, drop the original columns sx and dg
df1.drop(['sx','dg'], axis = 1)

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  ... 11 15 16 doctorate
0          NaN        NaN        NaN       male  ...  0  0  0         0
1          NaN        NaN        NaN       male  ...  0  0  0         0
2          NaN        NaN        NaN       male  ...  0  0  0         0
3          NaN     female        NaN        NaN  ...  0  0  0         0
4          NaN        NaN        NaN       male  ...  0  0  0         0
5          NaN        NaN        NaN       male  ...  0  0  0         0
6          NaN     female        NaN        NaN  ...  0  0  0         0
7          NaN        NaN        NaN       male  ...  0  0  0         0
8          NaN        NaN        NaN       male  ...  0  0  0         0
9          NaN        NaN        NaN       male  ...  0  0  0         0
10         NaN        NaN        NaN       male  ...  0  0  0         0
11         NaN        NaN        NaN       male  ...  0  1  0         0
12         NaN        NaN        NaN       male  ...  0  0  0         0
13         NaN        NaN        NaN       male  ...  0  0  0         0
14         NaN        NaN        NaN       male  ...  0  0  0         0
15         NaN        NaN        NaN       male  ...  0  0  0         0
16         NaN        NaN        NaN       male  ...  0  0  0         0
17         NaN        NaN        NaN       male  ...  1  0  0         0
18         NaN        NaN        NaN       male  ...  0  0  0         0
19         NaN        NaN        NaN       male  ...  0  0  0         0
20         NaN        NaN        NaN       male  ...  0  0  1         0
21         NaN        NaN        NaN       male  ...  0  0  0         0
22         NaN        NaN        NaN       male  ...  0  0  0         0
23         NaN     female        NaN        NaN  ...  0  0  0         0
24         NaN        NaN        NaN       male  ...  0  0  0         0
25         NaN        NaN        NaN       male  ...  0  0  0         0
26         NaN        NaN        NaN       male  ...  1  0  0         0
27         NaN     female        NaN        NaN  ...  0  0  0         0
28         NaN        NaN        NaN       male  ...  0  0  0         0
29         NaN        NaN        NaN       male  ...  0  0  0         0
30         NaN     female  assistant         10  ...  0  0  0         0
31         NaN        NaN        NaN       male  ...  1  0  0         0
32         NaN        NaN        NaN       male  ...  0  0  0         0
33         NaN     female  associate        NaN  ...  0  0  0         0
34         NaN     female  associate        NaN  ...  0  0  0         0
35         NaN        NaN        NaN       male  ...  0  0  0         0
36         NaN     female  assistant        NaN  ...  0  0  0         1
37         NaN        NaN        NaN       male  ...  0  0  0         0
38         NaN        NaN        NaN       male  ...  0  0  0         0
39         NaN        NaN        NaN       male  ...  0  0  0         0
40         NaN        NaN        NaN       male  ...  0  0  0         0
41         NaN        NaN        NaN       male  ...  0  0  0         0
42         NaN        NaN        NaN       male  ...  0  0  0         0
43         NaN     female  assistant        NaN  ...  0  0  0         1
44         NaN        NaN        NaN       male  ...  0  0  0         0
45         NaN        NaN        NaN       male  ...  0  0  0         0
46         NaN     female  assistant        NaN  ...  0  0  0         1
47         NaN     female  assistant        NaN  ...  0  0  0         1
48         NaN        NaN        NaN       male  ...  0  0  0         0
49         NaN     female  assistant        NaN  ...  0  0  0         1
50         NaN     female  assistant        NaN  ...  0  0  0         1
51         NaN     female  assistant        NaN  ...  0  0  0         1

[52 rows x 31 columns]

In [14]:
#Also, drop one of the dummy columns created for sx and dg variables
df1.drop(['doctorate','15'], axis = 1)

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  ...  sl 10 11 16
0          NaN        NaN        NaN       male  ... NaN  0  0  0
1          NaN        NaN        NaN       male  ... NaN  0  0  0
2          NaN        NaN        NaN       male  ... NaN  0  0  0
3          NaN     female        NaN        NaN  ... NaN  0  0  0
4          NaN        NaN        NaN       male  ... NaN  0  0  0
5          NaN        NaN        NaN       male  ... NaN  0  0  0
6          NaN     female        NaN        NaN  ... NaN  0  0  0
7          NaN        NaN        NaN       male  ... NaN  0  0  0
8          NaN        NaN        NaN       male  ... NaN  0  0  0
9          NaN        NaN        NaN       male  ... NaN  0  0  0
10         NaN        NaN        NaN       male  ... NaN  0  0  0
11         NaN        NaN        NaN       male  ... NaN  0  0  0
12         NaN        NaN        NaN       male  ... NaN  0  0  0
13         NaN        NaN        NaN       male  ... NaN  0  0  0
14         NaN        NaN        NaN       male  ... NaN  0  0  0
15         NaN        NaN        NaN       male  ... NaN  0  0  0
16         NaN        NaN        NaN       male  ... NaN  0  0  0
17         NaN        NaN        NaN       male  ... NaN  0  1  0
18         NaN        NaN        NaN       male  ... NaN  1  0  0
19         NaN        NaN        NaN       male  ... NaN  0  0  0
20         NaN        NaN        NaN       male  ... NaN  0  0  1
21         NaN        NaN        NaN       male  ... NaN  0  0  0
22         NaN        NaN        NaN       male  ... NaN  0  0  0
23         NaN     female        NaN        NaN  ... NaN  0  0  0
24         NaN        NaN        NaN       male  ... NaN  0  0  0
25         NaN        NaN        NaN       male  ... NaN  0  0  0
26         NaN        NaN        NaN       male  ... NaN  0  1  0
27         NaN     female        NaN        NaN  ... NaN  0  0  0
28         NaN        NaN        NaN       male  ... NaN  0  0  0
29         NaN        NaN        NaN       male  ... NaN  0  0  0
30         NaN     female  assistant         10  ... NaN  0  0  0
31         NaN        NaN        NaN       male  ... NaN  0  1  0
32         NaN        NaN        NaN       male  ... NaN  0  0  0
33         NaN     female  associate        NaN  ... NaN  0  0  0
34         NaN     female  associate        NaN  ... NaN  0  0  0
35         NaN        NaN        NaN       male  ... NaN  0  0  0
36         NaN     female  assistant        NaN  ... NaN  0  0  0
37         NaN        NaN        NaN       male  ... NaN  0  0  0
38         NaN        NaN        NaN       male  ... NaN  0  0  0
39         NaN        NaN        NaN       male  ... NaN  0  0  0
40         NaN        NaN        NaN       male  ... NaN  0  0  0
41         NaN        NaN        NaN       male  ... NaN  0  0  0
42         NaN        NaN        NaN       male  ... NaN  0  0  0
43         NaN     female  assistant        NaN  ... NaN  0  0  0
44         NaN        NaN        NaN       male  ... NaN  0  0  0
45         NaN        NaN        NaN       male  ... NaN  0  0  0
46         NaN     female  assistant        NaN  ... NaN  0  0  0
47         NaN     female  assistant        NaN  ... NaN  0  0  0
48         NaN        NaN        NaN       male  ... NaN  0  0  0
49         NaN     female  assistant        NaN  ... NaN  0  0  0
50         NaN     female  assistant        NaN  ... NaN  0  0  0
51         NaN     female  assistant        NaN  ... NaN  0  0  0

[52 rows x 31 columns]